#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* アドレス

  その日，Kは40本目の判決書にとりかかっていた。AIの進歩により，文章そのものは半自動で生成してくれる。一旦文章ができあがってしまえば，あとは細かな修正と署名さえすればいい。問題は，量刑の判断はK自身が行わなくてはならない，ということだ。これが面倒だ。Kが担当する公判は今年に入って1日あたり100件を超えた。全ての内容を把握することなんかできるわけないし，裁判そのものも大抵は自動音声が代わりにうまく進行してくれる。量刑さえ決まってしまえば文章だって代わりに書いてくれる。もはや全てを任せてしまってもいいのではないか。そう思うこともある。それでも判決そのものは人間であるK自身が下さなくてはならないのだ。あと署名も。

  判断に迷う微妙な事例だってしょっちゅうある。悩まない夜を過ごしたことはない。人の人生がかかっているのだ。それでもなんとか決定を下すと，それに則った文章をAIが瞬時に作成する。すると，たまに自分さえも気づかなかった要点を押さえた見事なものに仕上がっていることがある。そんなとき，Kは複数の判決書を作成してもらって，それを読みくらべて最終的な結論を下したいと思うのだ。ただそれは許されない行為だ。裁判官は己が良心に従う。それが司法の基本なのだ。AIの作成した字の羅列などに判断が惑わされてはならない。事実，Kが使用しているソフトウェアも，一旦下した結論が覆せないよう，AIが文章を作成した瞬間にいくつかのロックがかかり，その決定が中央に送信される。判決書の内容を修正することはできるけれども，主文そのものに手を加えることは決してできない。ゆえに，複数の文章を見比べることは許されないのだ。

  Kはその仕様が司法の尊厳を守るものであるとわかっているとはいえ，歯がゆい思いだった。今後自分が関わる裁判はますます増える。それなのに，負担の軽減をどれだけ訴えようと上が聞き入れることはない。法廷とは，人が普段隠している奥の奥までさらされる世界でありながら，当のK本人は誰からも拒まれているような，そんな居場所のなさを感じていた。

  <br>

  半年ぶりに帰った自宅で掃除をしていると，背後でガチャン，と何かが落ちてばらける音がした。振り向くと，祖父が使っていた工具セットが，その中身を床にぶちまけていた。面倒な仕事が増えた，掃除機が気づく前に拾わなくては，と思いながらドライバーやレンチを集めていると，ふと一本のマイナスドライバーが目に留まった。足元にやってくる掃除機を蹴飛ばし，その滑らかな表面を眺める。

  そうだ。Kは何かをひらめいた。

  <br>

  Kの祖父は古典的なものの考えをする人間で，魚を刃物で解体したり，車両のパンクを修理するといった人間ばなれした能力をいくつも持っていた。Kはそんな祖父が超能力者のように思え，両親が嫌がるのも気にせず祖父に会いに行っては，様々な道具の使い方を学んだ。Kが持っている工具は，そんな祖父から譲られたものである。

  Kは事務所の電源を予備まで落とす。そして机の端末を裏返すと，金属の円に線が入っているのを発見した。確か，動く方向に回せばよかったはずだ。Kはドライバーを使って器用に外してゆく。取り外されたそれは，先端に渦のような模様が入っていた。ええと，このあと祖父は「外したもんは無くしたらいかんよ」と言っていた。工具箱にでも入れておけばよいか。

  いくつかの金属片を取り外すと，薄い板が盛り上がった。慎重にそれを横にずらすと，見たことのないおぞましい臓器がのぞいた。思わずKが目をそらす。臓器ではない。回路，というやつだ。こんなに気味の悪いものだったのか。

  その気色悪い模様を眺めながら，Kはどこかに判決書生成プログラムへの手がかりがないか探す。ふと眼球の解析装置が反応した。回路の複数の箇所に，線の組み合わせられたものが規則的に並んでいる。装置はそれを言語だと伝えている。ではこれが文字というやつか。もはや人間にとって，言語は心的な信号として扱われることしかなく，Kが外的に記録された言語を見たのはこれが初めてだった。それにしても，装置さえも反応しない，この円のような記号は何だろう。

  Kの体内の端末を使って取り込んだ記号を検索する。すると，この記号は，はるか昔，通信の際に識別番号を示すものとして使われていたらしい。では，この短い記号の羅列で個々が識別できたということか。文字とは想像以上に情報を圧縮する能力があるようだ。ただ，Kはそれほど古い通信規格が今でも使われていることに驚異をおぼえるとともに，検索をかけてもわからない，その番号の持ち主が誰か知りたくなった。おそらくその人物，もしくは組織が，判決書生成プログラムと関わっているはずだ。

  <br>

  Kは役所を訪れた。あれだけの古い通信規格を今でも使っていそうな場所は，Kの知るかぎりここしかない。

  博物館にあるような電動式のドアを入ると，なかでは人々がせわしなく働いている。これほど多くの人をこんな狭い場所に閉じこめておくなんて，さすが公的組織というべきか。そう思うとともに，これだけの人に一度に会うこと，そこに懐かしさもおぼえた。

  「よう，K」

  その声にKは顔を向けた。ガラガラと黒い円筒型の機械がやってくる。そこに取り付けられたディスプレイには笑顔が映し出されていた。

  「久しぶりだな，T」

  TはKの親友で，今はこの役所に勤めている。「話は聞いたぜ。メールしたい相手がいるんだろ」「メール？あの通信はメールっていうのか。変な響きだな」「そうかもしれんな。まあ，世間話は奥でやろう。ここはお前のようなやつが来る場所じゃないからな」

  お前のようなやつ，という言葉にKはひっかかるものがあったが，とりあえず礼はしておかなくては。そう思い，Tのために用意した最適化プログラムを送信しようとしたが拒絶される。

  「あれ？」「ああ，俺の身体はそのデータ形式にはまだ対応していない。あとでICチップを渡すから，それで送り返してくれよ」

  ICチップ。Kははるか昔にタイムスリップしてきたような奇妙な感覚に立ちくらみがするようだった。

  <br>

  Tは狭い机にケーブルをつなぎ，何らかのデータのやりとりをしている。「まだ終わらないのか」「もう少し待てよ。…よし，つながった。それじゃあそのメールアドレスを教えてくれ」「アドレス？」「識別番号のことだ」

  Kは腕を組む。「どうやって送ればいいだろう」その答えにTも唖然とした。「何も考えてなかったのか」「Tと通信できないとは思っていなかったからな」「じゃあICチップを渡すからそれに」「それを接続するものがない」

  二人を沈黙が支配する。

  「そうだ」Tが何かをひらめいた。「お前の眼球はまだナマモノだったな」「その言い方はやめろ」「瞳孔の収縮を使って俺が記号を読む。それならできるだろ」

  心的な言語に応じた微妙な瞳孔の変化。それを少しずつ読み取るのだ。はるか昔，KとTが二人で身につけたカンニングの秘策である。

  「それしかないか」Kがあきれるように言う。その効率の悪さが許されたのはテストのときだけだ。仕方なく目を見開き，Tのディスプレイに近づける。

  「もうちょっと近づけ」「こうか」「もう少し」「随分性能の低いカメラだな」「もうちょっと」

  ふいにKが顔を離す。「お前，何か変なこと考えてないか？」「，そんなことないぞ」「今の間は何だ」

  <br>

  その後，Kの瞳を介して番号を読み取ったTは，机のモニタに記号を羅列させてゆく。なんと手間のかかることか。役所に来てからこれまでのやりとりで何本の判決書が書けただろう。「送ったぞ」そう言ってTがKに向き直った。「返事は」「まだだ」「まだだって，送ったんだろう？」「メールってのはな，荷物みたいなもんなんだ。届いたことを相手が確認して，それに返事を書いて送り返さなきゃいけない。どうしても時間がかかる」

  Tはわかるように説明したつもりだが，Kは理解できないようだった。「荷物なんて待った覚えがないが」Tはため息をついた顔をディスプレイに浮かべる。「それはお前のアシスタントが事前に予測して配達を注文しているからだ。だから注文してすぐ届いたように見える」「そうなのか。いろいろ詳しいな，お前は」「お前はもうちょっと世の中に詳しくなったほうがいいぞ」

  Kの顔がふいに曇った。「余計なお世話だ」

  失言だった。ただどこが気にさわったのかTにはわからない。Kのおかれた状況を知らないからだ。

  それでも落ち込んだKにTが申し訳なさそうに謝る。「す，すまんな。ほら，俺にはもう肉体がないからな。人間の気持ちに疎くなってるだけだから。気にすんな」Tがケーブルを左右に動かして，おどけた態度を取る。

  Kはようやくふっと微笑み，「器用な身体だな」とTをつついた。

  <br>

  それから互いの近況を含め，二人は休憩室で話し合った。Kに自販機の飲み物を買う方法はなかったが，Tが代わりにおごった。謝罪の気持ちということで。KはTと会話をするなかで，からまっていたものがほぐれるような気持ちだった。

  「お前，子供は作らないのか」Tがふいにたずねた。Kは一口飲んで，「いや」，と壁を見たまま答える。

  「そうか。でもお前，子供好きだったよな」「…そうだな。そうだったかもしれない」「今でもお前が有機体なのは，まだ未練があるからだと思っていたが。違うのか？」「色々忙しいしな。それに，人間の身体のほうが俺の仕事には合っている」

  するとTが意地悪そうな顔をした。「そりゃそうかもな。ストレス発散とか」それを聞いたKが怪訝な顔をする。「何のことだ。もしかしてお前，さっき目を見たとき」「お前らはもう少し情報の隠し方を学んだほうがいいぜ」

  Kが真っ赤な顔でTの身体をゆさぶる。「何を見た。正直に言え。そして今すぐ消せ」「いやあ，いいもん見せてもらったぜ。あんなの機械の俺らには到底真似できない」

  Kは恥ずかしさのあまりTを蹴飛ばした。その身体がゴロゴロと転がってゆく。と，フロア全体にけたたましいブザーが鳴った。

  「あーあ。やっちゃったな」Tが壁にぶつかって静止しながら言う。「すまん」我に返ったKが謝る。Tが横になったまま，ケーブルを伸ばして向かいの壁を指す。「そこのダクトから出られる。早く行け」「そんな。俺は」「行け!」

  おずおずとKは言われるまま，通気口を開けて身体を押し込む。だが尻がひっかかる。「K」後ろからTが呼びかけた。

  「後悔しない選択をしろよ」

  その言葉に後押しされるように尻が入口を抜けた。

  <br>

  

  <br>

  -- 了 --

  <br>
  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
