#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 煌帝

  煌帝 (こうてい) は四大精霊を従えた輝ける王であり，この世を遍く統べる神・大空神 (だいくうしん) に唯一匹敵する力を持つものである。その容姿は並ぶものがなく，またたく間に精霊が虜となるほどであった。だが煌帝は世を治めることに関心を持たず，己が精霊とともに離宮で悦楽の日々を送っていた。力の根源と存分に交わることのなんと心地良いことか。

  離宮は誰にも開かれている。だが誰を受け入れるわけでもない。精霊の気に障ることがあれば，何をせずとも葬られる。果たして煌帝とはいかな姿であったか。時とともにその顔や声も忘れられ，ただあの離宮には煌帝が暮らす，という話のみが残った。そしてそこへの道もやがて朽ち，誰も訪れる者はなくなった。

  流浪の詩人チルはさびれた酒場でそんな話を聞いた。精霊の恵みは絶えて久しく，人々は鉄の力によって争いを続けながらも滅びることなくその命をつないでいた。行く先は大空神ピシトーの知るところではない。いや，当然知っていようが，もはや熱を失った人への興味をなくしたのだろう。それに応じるように，ピシトーを称える最後の神殿も先の戦で瓦礫へと姿を変えてしまった。

  血とパンと憎しみと涙とわずかな幸せでのみ紡がれつづける自らの詩にチルは憤っていた。あの素朴に自然と調和した，古典にのみ残された詩，今は化石と呼ばれていようが構わない，あの詠むだけで力がわくような，活力あふれる詩，それを生み，そして吟じる力を自身に宿したいと思った。

  <br>
  <br>

  陽もささぬ棘の森，踏み外せば奈落へ落ちる崖を経て，ようやくチルは煌帝の離宮へとたどり着いた。荒廃した景色にたいし，塔は美しく輝きを放ち，できた当初のありようそのままに天までそびえている。触れれば指紋が残るのではないか，と思うほどに磨かれた門を押し，中へと入った。

  かぐわしい香りと水のざわめき。草木のかなでる優雅な調べ。広大な空間は生きるものの息吹に満ちあふれている。その若々しさと艶かしさのいりまじる圧倒的な情景を，チルはよだれが垂れるのも構わず全身で堪能していた。

  「誰じゃ」

  頭のてっぺんから足の先まで伝わるような，針のように鋭い声に，チルははっと我を取り戻した。中央の天蓋に，薄い膜がなびき，誰かの姿がある。

  四人の神，いや，美しき精霊に囲まれ，何かが布をかぶせられている。

  それを膝にのせる者。ただ寄り添う者。たおやかに手で仰ぐ者。そして愛おしそうになでる者。布の下に何があるのかは明らかである。

  精霊に優しくふれられるだけで，また心ある言葉をかけられるだけで至上の快楽となるのだ。それを独り占めしている様子があまりにもうらやましく感じ，見とれていると，精霊の一柱があおいでいた腕をこちらにふっと凪いだ。

  ぶわっ。

  急に何かの圧迫感が迫り，チルは声を出せなくなった。いくつか煌帝に取り入るための言葉を用意してきたはずなのだが，全て頭から消え去ってしまう。

  「何用じゃ，と申しておるのだが，そちは口なしかえ」

  「あ…」かたかたと震えるばかりだったが，ガチッと舌を噛み，「詩人のチルと申す。陛下に我が自慢の詩を披露するために，遠くからやって参った」とようやく言葉を発した。だがそれはあまりにも無粋な，そしてチルの本心を示した言葉であった。精霊の前で隠し事などできないのだ。

  「陛下はお休みになられておる」布をなでながら別の精霊が話した。「それにそちはずいぶんと無礼な口をきくようじゃな。ここにおられるのが誰かわかっておるのか」

  「輝ける王の中の王，太陽の化身，過去から未来の万物全てを照らしだす，至上の煌帝陛下であらせられます」

  「そうじゃ。それをその穢れた口で何を吟じようというか」また別の精霊が話した。

  「陛下が離宮におかくれになられてからの人の歩み，ここにいる皆々様のまだ見ぬ景色でございます」

  「陛下はそのようなものなど召さぬ。あさましき肉の戒めなど」

  ぱたっ。

  布から何か黒いものが垂れた。「陛下」あわてて精霊がすべらかな手を差し出したが，何かの気配を感じ，ふれるのも畏れ多いといったようにその手を引っこめてしまった。

  布から垂れたもの。それは，棒切れのような，細くただれた腕であった。

  「よかろう，そこの者。陛下に吟じてみせよ」

  そう四人目の精霊が言うと，急に照明が落ちたかのようにあたりが暗闇に包まれた。精霊も姿を消し，純白の布と，そこから垂れた腕だけが照らし出されたかのように光を放っている。

  この世界にはいま，チルとその腕のみが在る。全てが試されている。

  チルは噛んだ舌の感触を確かめると，息を吸って詩を歌った。

  精霊を失った人々の困惑。互いの正義。争い。滅び。くじけぬ心。鉄の時代。なお絶えず流れる血。欲望。後悔。苦痛。懺悔。なお生まれる希望。命。幸せ。そして救い。

  チルが歌ったのは，生まれる前から故郷では戦乱が絶えず，瓦礫のなか，土煙のまぶされたパンで飢えをしのぎながら，なお，いつか故郷が緑と水と笑顔にあふれたものとなる，故郷に生まれた者の誰もが夢にさえ思ったこともない，未来への願いだった。

  <br>

  ぶわっ，と再び何かの迫る感じとともに，世界は一瞬でもとの輝きを取り戻した。草花も，水のせせらぎも，そして精霊も。ただ，垂れた黒い腕だけが見えなくなっていた。

  ふとチルは握りしめた手の中に何かの感触があった。手元で開くと，七色に光る大きな宝石である。

  「陛下は良い心地であったそうじゃ。それは褒美じゃ。受けとるがよい」

  <br>

  チルはそれから精霊達に礼を言って離宮を出ると，崖下に宝石を投げた。

  <br>
  <br>

  -- 了 --

  <br>
  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
