#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 片鋏のやどかり

  若狭の漁師に生まれた真は，幼い頃より誰よりも深くまで潜ることを好んだ。
  父を亡くし，母と二人で暮らしながらも，長じて素潜りの名人となることを
  夢見ながら，毎日のように海へ入った。

  その年はサザエが多く採れた。懐も温かくなった母は真に金を持たせ，せっ
  かくの機会だから町を見てくるよう言った。父が真のために残していた服を
  着て，真は一人で町へ行った。町は人と音が絶えず，すべてが目に鮮やかだっ
  た。真は自身のみすぼらしさを恥じて，一晩で帰ろうと思った。

  ところがその夜から空が急変し，数日にわたって町から帰る道が雨で閉ざさ
  れてしまった。真がようやく家に帰ると，壁と屋根の一部を残して流されて
  しまっていた。近所の人がやってきて言うに，母の姿が見えぬ。真はそれを
  聞いて平静だったので，人は真を奇妙に思った。

  一人になってしまった真は，近所の船を手伝いながら，家を直し，月の明る
  い夜に潜る日々を送った。時折真夜中に波間から狼のほえるような声がする
  のは，真のものだったのかもしれぬ。

  やがて真は体格も整って，自らの身体で稼げるようになった。町へ出ること
  も多くなり，そこでの付き合いも学んだ。ただ，真の心には常に深い海があっ
  た。町へ行くことはあっても，家から離れることはなかった。

  その年，サザエが多く採れた。人々は不吉を感じた。事前に避難する者もあっ
  た。ある人が真の元にもやってきたが，真は「母を待つ」と一言いったきり
  家から現れなかった。そしてある日の夜，空がむやみやたらに大水を吐き出
  してきた。多くの人は避難し無事だった。だが真の姿がみえぬ。母に次いで
  真までも。人々は真の無謀を思いつつも，無事を祈った。

  真が家で母を待つという気持ちは本当であった。すでに家はほとんど流され，
  真は無心で柱にしがみついていた。猛雨ゆえに，自身がいるのが海か陸か判
  然としなかった。ただひたすらに母の迎えを待った。

  どれほどの時が経ったか。ふっと雨音が消え，明るくなった。波音さえ聞こ
  えぬほどの静寂であった。真はついに迎えがきたかと目を開いた。

  目の端いっぱいに月が広がっていた。下半分は海にすっぽりと覆われ，波な
  き面が月を反射している。はたしてこれがあの世というものか，と真は思い，
  同時にえもいわれぬ平穏を感じていた。

  翌朝，崩れた家の柱に真が倒れているのが見つかった。誰もが悲劇を覚悟し
  た。だが真は生きていた。起きあがると，真は海を見た。いつもの波間があ
  る。真は周りに人がいないかのように，問いかけに応えず，海へ向かった。

  ふと足下の砂浜に，片腕を失ったやどかりが歩んでいた。それを見て，真は
  母を待つのをやめ，町で暮らすことにした。

  <br>

  -- 了 --

 

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
