#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 怪獣の国

  学校からの帰り道，電柱のそばで泣く緑の怪獣に出会った。

  「どうして泣いているの」怪獣はとがった爪の隙間から，ぎょろりとした目をのぞかせる。「ぐすっ…あなたは？」

  「私はヌー。いつものんびりしてるからヌー」怪獣は声をかけてくる相手の身体を頭から足先までながめてから，「あなたは私が見えるんですか」と言った。ヌーは周囲を見回す。こんな物がいれば見逃すはずもないが，とはいえ，こんな昼間に歩く者など誰もいない。「みんなはあなたが見えないの？」

  「はい。友だちがほしくて，せっかくここまで来たのに，誰も私に気づいてくれないんです」「友だちがほしいの？」「はい」

  「じゃあ私が友だちになってあげるよ」そう言ってヌーは泥だらけの手をはらって怪獣に差しのべた。「ほんとうですか。私の友だちに」「うん」「ありがとう，ヌー」

  怪獣は鋭い爪の生えた手を伸ばし，握手をしようとした。ヌーはすかさず逆の手で怪獣の手の甲をつかみ，「これで友だちだね」と笑った。

  <br>

  怪獣は都会から来たそうだ。だが誰に話しかけても，みんな，ぎょろりとした目のついた四角い板をいじるばかりで，怪獣の話を聞いてくれない。そうして何日も歩きながらここまで来てしまった。

  「私はその板を持ってないから，怪獣さんが見えたのかもしれないね」ヌーは片手で板を持つ振りをし，指で手の平をなぞった。

  「あの，もし，ヌーさんが良ければ，私の住んでるところに来ませんか」怪獣は牙を見せながら，爪でウロコだらけの顔をゴリゴリとこすった。「いいよ。私も行ってみたい」ヌーの言葉に，怪獣は目を細めて喜んだ。「でも，そんなに遠くまでは行けないよ。お母さんが心配するから」

  「心配なく。すぐに着きますから」そう言って怪獣は大きな口を開けた。ノドの奥は真っ暗な闇へとつながっている。「私の口にお入りなさい。そこから私の暮らしている場所に行けます」

  「私を食べてもおいしくないよ」「ここから入らないと，何千万年も旅をすることになりますが」「そんな長い間生きていられない」「ではどうぞ」怪獣は口の端を爪でクイクイと指す。

  仕方なくヌーは上半身だけを開いた口に乗せようとした，途端に何かに引き込まれるような力があって，あっという間に全身が飲まれてしまった。

  <br>

  「ヌーさん，着きましたよ」怪獣の声にヌーが目を覚ますと，あたたかな日射しが差し込む森の中だった。ただ暖かいのに妙に身体がひんやりする。それは湿った葉の露がへばりついたからではない。「わ，私の服は」思わずヌーは茂みにしゃがみこんだ。「私の国ではみんなそうですよ」怪獣は自分も同じとばかり，自らの身体を指す。「でも，これじゃあ帰れない」「それならば，帰るときに代わりの服を仕立てましょう。ついてきてください」

  怪獣の手首をつかみ，もじもじしながらその後を追う。怪獣の言うことももっともで，間もなくヌーの身体は汗ばみ，ぽたぽたと雫が垂れてきた。むせかえる熱気に，空気が腕となって肺をつかんでくるように思えた。

  やがて森を抜け，眩しい光が目につきささってくる。「わあ」ヌーは声をあげてしまった。見渡すかぎりの草原に，どこまでも頭が見えないほど大きな怪獣，その足元をかけまわる二本足の小さなトカゲたち，そして大空を舞う黒い影の群れ。

  その足音と振動。波紋のように流れてくる鳴き声。鼻をさすニオイ。全身を伝わる風に内側から熱くなるような，じっとしていられない気持ちになった。こんな場所を誰にも邪魔されず，何日でも駆け回ることができたら。

  そうして歩きだそうとするヌーの手を怪獣が掴んだ。ヌーはその手を外から握りかえす。

  「こっちですよ」怪獣は急かすように言って，森を片側にして進み出した。その足は速く，ヌーは何度もこけてしまいそうになる。「どうしたの。もう少しゆっくり見ていこうよ」

  その理由はすぐに明らかになった。

  「おい」ガサガサという音をたて何かが二人の前に立った。さっきのトカゲたちだ。その低い声は好意的なものではない。

  「おい」再びからかうような呼びかけをし，ぎょろりとした目でこちらを見る。「暴れん坊が帰ってきたぞ」「なんだその後ろのやつは」「仲間か」「エサか」「弱そうだ」「ウロコがない」「尻尾もないぞ」

  怪獣が目を合わせず避けようとするのを，トカゲたちは先回りして通さない。ヌーは目を伏せて黙り込んでいる。そんな様子にトカゲたちは調子づき，囃したてた。「おい」「なんか言えよ」「頭にしか毛が生えてないくせに」「おい」「暴れてみろよ」「泣くか？」「びびってるか？」「びびってる」「弱虫」

  ヌーは顔を伏せたまま，ぽろぽろと涙を流しはじめた。それでも両手で覆ってなんとか声を押しころす。悔しかった。

  「がうっ」

  腹まで響くような音が鳴り響き，わっと言ってトカゲたちが離れた。ヌーの顔を覆う手を握り，怪獣はそのまま開いた隙間を抜けてゆく。

  「怒った」「おい」「もう一度吠えてみろよ」「がうがう」トカゲたちはヌーの後ろからどやしながら追いかけてくる。けれども怪獣の足は止まらない。「弱虫」「泣き虫」

  それでも無視しつづける二人にやがて飽きたのか，トカゲたちは追うのをやめた。その姿が小さくなってゆく。

  <br>

  ヌーは腕のケガを湧き水で流していた。「強く掴んでしまって，ごめんなさい」申し訳なさそうに謝りつづける怪獣に気にしないよう言ったものの，手首にはいくつもの切り傷がついて痛々しい。

  流れる水を眺めながらヌーは怪獣に聞いた。「ねえ，私を見てどう思う？」「す，すみません。けがのせいで見た目が変わってしまったのなら」平謝りをつづける怪獣に，ヌーは首を振る。

  ヌーは学校でもさっきと同じようなめにあっていた。何度も。だから今日だって学校をさぼったのだ。ヌーは自分がのんびりした性格なのはわかっているが，でもみんなにそれを悪く言われると，なぜか悲しかった。

  そんな自分はここへきてもからかわれている。何か自分はダメなところがあるのだろうか。だから友だちである怪獣に正直なところどう思うのか，答えてほしかったのだ。

  その言葉を聞いて怪獣は腕組みをして考える。「うーん…，あ」「なに？」「もしヌーさんがみんなと同じように急いでいたら，私に気づかなかったかもしれません」「え」「私が会った人たちはみんな大忙しでしたから」

  何かに注意していると，場違いな物が視界に入っても気づかない。ヌーはいつものんびりしているからこそ，怪獣に気づけたのかもしれない。

  「ところでケガの具合はどうですか」「冷やしたから，血は止まった，と思う」「よかった。私の家はすぐそこですよ。そこで手当てしましょう。いいですか」ヌーの質問をはぐらかすように怪獣は言い，拳を握るようにして手をさしのべた。爪で傷つかないように。

  ヌーは怪獣の手を包むように握り，案内にしたがって歩きだした。

  <br>
  <br>

  -- 了 --

  <br>
  <br>

  原案: 小林さんちのメイ曲集「迷子のかいじゅう」 

  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
