#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 怪獣の国

  学校からの帰り道，電柱のそばで泣く緑の怪獣に出会った。

  「どうして泣いているの」怪獣はとがった爪の隙間から，ぎょろりとした目をのぞかせる。「ぐすっ…あなたは？」

  「私はヌー。いつものんびりしてるからヌー」怪獣は声をかけてくる相手の身体を頭から足先までながめてから，「あなたは私が見えるんですか」と言った。ヌーは周囲を見回す。こんな物がいれば見逃すはずもないが，とはいえ，こんな昼間に歩く者など誰もいない。「みんなはあなたが見えないの？」

  「はい。友だちがほしくて，せっかくここまで来たのに，誰も私に気づいてくれないんです」「友だちがほしいの？」「はい」

  「じゃあ私が友だちになってあげるよ」そう言ってヌーは泥だらけの手をはらって怪獣に差しのべた。「ほんとうですか。私の友だちに」「うん」「ありがとう，ヌー」

  怪獣は鋭い爪の生えた手を伸ばし，握手をしようとした。ヌーはすかさず逆の手で怪獣の手の甲をつかみ，「これで友だちだね」と笑った。

  <br>

  怪獣は都会から来たそうだ。だが誰に話しかけても，みんな，ぎょろりとした目のついた四角い板をいじるばかりで，怪獣の話を聞いてくれない。そうして何日も歩きながらここまで来てしまった。

  「私はその板を持ってないから，怪獣さんが見えたのかもしれないね」ヌーは片手で板を持つ振りをし，指で手の平をなぞった。

  「あの，もし，ヌーさんが良ければ，私の住んでるところに来ませんか」怪獣は牙を見せながら，爪でウロコだらけの顔をゴリゴリとこすった。「いいよ。私も行ってみたい」ヌーの言葉に，怪獣は目を細めて喜んだ。「でも，そんなに遠くまでは行けないよ。お母さんが心配するから」

  「心配なく。すぐに着きますから」そう言って怪獣は大きな口を開けた。ノドの奥は真っ暗な闇へとつながっている。「私の口にお入りなさい。そこから私の暮らしている場所に行けます」

  「私を食べてもおいしくないよ」「ここから入らないと，何千万年も旅をすることになりますが」「そんな長い間生きていられない」「ではどうぞ」怪獣は口の端を爪でクイクイと指す。

  仕方なくヌーは上半身だけを開いた口に乗せようとした，途端に何かに引き込まれるような力があって，あっという間に全身が飲まれてしまった。

  <br>

  「ヌーさん，着きましたよ」怪獣の声にヌーが目を覚ますと，あたたかな日射しが差し込む森の中だった。ただ暖かいのに妙に身体がひんやりする。「わ，私の服は」「私の国ではみんなそうですよ。心配なく」「これじゃあ帰れない」「では帰るときに仕立てましょう。ついてきてください」

  怪獣の手首をつかみ，もじもじしながらその後を追う。怪獣の言うことももっともで，間もなくヌーの身体は汗ばみ，ぽたぽたと雫が垂れてきた。

  やがて森を抜け，眩しい光が目につきささってくる。見渡すかぎりの草原に，どこまでも頭が見えないほど大きな怪獣，その足元をかけまわる小さな怪獣，大空を舞う黒い影の群れ。

  <br>
  <br>

  -- 了 --

  <br>
  <br>

  原案: 小林さんちのメイ曲集「迷子のかいじゅう」 

  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
