#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 最後のモーサル

  人類による汚染は進み，保護された希少生物モーサルの数も残りわずかとなっ
  た。なるべく生息地に近い環境を与えられたが，集団で生活するモーサルに
  とって好ましい状況ではなく，日に日に弱っていった。

  モーサルは人類の近縁種であることは判明しているものの，いくつかの違い
  がある。モーサルは主に後ろ足で移動し，眼球の上に頭部がある。不安定な
  位置に脳があるために，知能の発達に限界があるのだ。また肉体を構成する
  主成分はタンパク質とカルシウムで，体表面には部位によって密度の異なる
  毛が生えている。

  モーサルは生物のなかでは高度な知能を持つ。一桁の乗算を暗算でき，鏡の
  認知や，誤信念課題を達成することができる。しかし四次方程式の解や，複
  数のデータに対する潜在変数モデリングを暗算で行うことはできない。また
  一度に保持できるデータ量も極めて少ない。

  集団生活を基本とするが，十分な統制はとれていないことが多い。そのため
  集団が長期的な視野にたって行動することができず，保護をしなくても絶滅
  していたのではないかという意見もある。

  それでもモーサルを保護しようという動きが出たのは，モーサルが人類より
  もはるかに発達した発声システムを持っていたためである。これは身体中央
  の肺から送り出した空気を頸部の膜で震わせて出力する仕組みなのだが，頸
  部の膜および咽頭部の筋肉を微妙なバランスでコントロールすることにより
  実に様々な音声を生み出すことができる。

  最近の研究では，モーサルが情報伝達の手段としてこの発声を日常的に使用
  していたことがわかっている。しかし当初は，障害物で軽減しやすく，消費
  エネルギーの多い発声という仕組みをモーサルが使用しているとは考えられ
  ていなかった。コミュニケーションの際にいかなる電波も検出されず，どの
  ように意思疎通を図っているかが大きな謎とされていたのである。
  
  その後の映像解析によって，モーサル同士が情報伝達を送っていると予想さ
  れる場面で何らかの振動が検出された。詳しく調査すると，その振動がモー
  サルが放った音波によるものであることが判明したのである。重力メカニズ
  ムの解明以来，音波の研究技術は時とともに失われた。モーサル研究のため
  に再びその技術が求められるようになったのである。
  
  音声を計測する装置が完成する頃には，モーサルは残り1頭となり，発声を
  記録することはほとんどできなかった。人類はなんとかしてモーサルの意思
  疎通の仕組みを解明しようと試みたが，音声のサンプル数が少なく，わかっ
  たのは音声に特定のパターンがあること程度であった。現在は残された映像
  を解析して音声の復元を試みようとする動きがある。

  最後のモーサルはあまり活動せず，毛布の中で過ごしていることが多かった。
  やがて食事もほとんど取れなくなった。排泄物は垂れ流しになり，定期的に
  洗浄しなければならなかった。抵抗もせず洗浄される様子から，その日が迫っ
  ていることは明らかであった。

  それから2日後の朝，モーサルは水を一口だけ飲み，その夜に死んだ。

  <br>

  -- 了 --

 

  <br>
  <br>
  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2016 jamcha (jamcha.aa@gmail.com).

  This document is licensed under the [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][Creative Commons Attribution Non Commercial Share Alike 4.0 International License]]

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png]]

