#+OPTIONS: toc:nil
#+OPTIONS: \n:t

* 会議

  会議は緊迫した空気がはりつめていた。度重なる赤字により経営は火の車であり，有効な手を打てない役員たちは窮地に追い詰められていたのである。

  当然ながら今回の会議も，いつものように互いに責任を押しつけるものになることが予想された。ところが，最も若い役員である鮎川が意外な一言を口にした。

  「今まで隠していましたが，わが社を立て直す方法がひとつだけあります」

  その言葉に会議室が色めきたつ。「どんな方法だ」「早く言え」「なぜ今まで隠していた」…。「鮎川くん，今はどんなアイデアでもありがたい。遠慮なく言ってもらえないか」最年長の小倉社長はそう言った。

  後ろめたいことがあるのか鮎川はためらっていたが，「まさか法に触れるものじゃないだろうな」という猪原の一言を否定し，その方法を打ち明かした。

  「皆さんの臓器を売ります」

  ばかな。そこにいる者だけではない。誰もが思うことだ。会社のために臓器を売るだと？あまりにもふざけたそのアイデアを，梅本が怒鳴りつけようとする。と，その声にかぶせるように，鮎川が話した。「皆さんは，昨年の赤字がその前年よりも少なくなっていることを不思議に思わなかったんですか」


  そう。特に計画を見直したわけでもないのに，昨年，見違えるように赤字が減少した。役員たちはそれを景気が上むいたことが原因だと思っていたのだが。「まさか」そう言う榎の顔は青ざめている。

  「私の臓器を売り，経費に当てました」鮎川は顔色ひとつ変えずに言った。「どうして俺たちに相談すらしないんだ」猪原が責める。「そうだ。勝手なことをしてぬか喜びさせて」梅本もすぐさまそれに合わせた。

  「それは，私が部下の痛みを知るためです」

  鮎川の言葉に力がこもる。なおも責めようと梅本は唇を濡らしたが，猪原の顔色を見て押し黙った。

  「我が社を維持するため，多くの社員が血を流してきました。次は私たちの番。そうじゃないんですか」

  それから鮎川は，全員の影の差した目を見ながら熱弁した。力不足の自分たちの責任を部下に押しつけ，これまで多くの犠牲を払って会社を維持してきた。今こそそのけじめをつけるときだと。若造が偉そうなことを。猪原と梅本が苦々しい顔をする。

  「それはどれくらいの金額になるのかね」小倉が沈黙を破って言った。「社長」榎が小倉を止めようとする。その声は驚きのあまり裏声になってしまった。

  鮎川が金額を口にする。そのあまりの大きさに全員が唖然とした。「一人分でそれか」その問いに鮎川が無言でうなずく。なんということだ。全員が差し出せば，債務の半分以上を返すことができる。「後遺症は残らないのか」「買い手はちゃんとしたやつなのか」「術後も酒は飲めるのか」矢継ぎ早に質問が繰り出され，その都度，鮎川は即座に返答する。

  部下からの信頼を取り戻すチャンスかもしれない。日々高圧的な態度で多くの敵を作ってきた猪原はそう考えた。「わかった。やろう」目を見開く梅本の隣で，腕組みをしながら猪原は言った。猪原がやるのなら，梅本も逆らえない。鮎川はうつむく榎の顔，考えこむ小倉の顔を見る。

  父から受け継いだ会社を自分の代で終わらせるわけにはいかない。小倉も覚悟を決めた。

  <br>

  鮎川に続き，四人も文字通り身体を切り売りしたことで会社の経営もわずかに持ち直した。しかし抜本的な行動はなされないままである。危険な状況に戻るまでさほど時間はかからなかった。

  <br>

  役員会議は以前よりも重苦しい雰囲気に包まれていた。これ以上身体を切り刻むのは無理だ。だが若き鮎川だけはその目に光を宿している。

  「まだ方法はあります。あきらめてはいけません」その言葉を何度聞いたことか。威勢のいい言葉を並べたて，口先三寸で金だけ奪っていくコンサルタントとかいう虚業の輩に，どれだけ騙されてきたか知れない。

  とはいえ，この前年も再び赤字が減少していたことに，小倉は一縷の望みをかけていた。書類の数字もいじれるところは全ていじった。事が明るみに出る前に，なんとか経営を立て直し，全てを煙に巻かなければ。

  「どんな方法をとったんだね」小倉は汗をぬぐいながら，鮎川に問う。すると，鉄仮面と呼ばれてきた鮎川の瞳から涙がこぼれ落ちた。

  「昨年，私は自動車事故を起こし，最愛の妻と娘を亡くしました」

  その場にいた全員が騒然とし，熱気のこもる部屋にも関わらず身体が震えだす。

  <br>
  <br>

  -- 了 --

  <br>
  <br>

  この物語はフィクションであり，実在の人物・団体とは一切関係ありません。

  Copyright (c) 2018 jamcha (jamcha.aa@gmail.com).

  [[http://creativecommons.org/licenses/by-nc-sa/4.0/deed][file:http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png]]
